"""
Django settings for pakwheelproject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^pgdcg+7v7_fq*#2hqbtz#)(zc)eqzx78a0sox8!&o@qlvpv0q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pakwheel',
    'carlisting',
    'authentification',
    'registration',
    'phonenumber_field',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pakwheelproject.urls'
LOGIN_URL = '/auth/login/'  # Adjust this to match your URL namespace


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'pakwheelproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pakwheels',
        'USER': 'postgres',
        'PASSWORD': 'hash0303',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CAR_BRANDS = [
    ('TOY', 'Toyota'),
    ('BMW', 'BMW'),
    ('MER', 'Mercedes-Benz'),
    ('HON', 'Honda'),
    ('AUD', 'Audi'),
    ('LEX', 'Lexus'),
    ('FORD', 'Ford'),
    ('CHE', 'Chevrolet'),
    ('VOL', 'Volvo'),
    ('MAZ', 'Mazda'),
    ('NIS', 'Nissan'),
    ('SUB', 'Subaru'),
    ('VW', 'Volkswagen'),
    ('JAG', 'Jaguar'),
    ('PORS', 'Porsche'),
    ('LAND', 'Land Rover'),
    ('RAN', 'Ram'),
    ('KIA', 'Kia'),
    ('HYU', 'Hyundai'),
    ('ACU', 'Acura'),
    ('LIN', 'Lincoln'),
    ('INFI', 'Infiniti'),
    ('MIN', 'MINI'),
    ('BU', 'Buick'),
    ('CAD', 'Cadillac'),
    ('MITS', 'Mitsubishi'),
    ('CHRY', 'Chrysler'),
    ('FIAT', 'Fiat'),
    ('ALP', 'Alfa Romeo'),
    ('MAS', 'Maserati'),
    ('AST', 'Aston Martin'),
    ('FERR', 'Ferrari'),
    ('TES', 'Tesla'),
    ('RAM', 'Ram'),
    ('SAAB', 'Saab'),
    ('GMC', 'GMC'),
    ('JEEP', 'Jeep'),
    ('PEU', 'Peugeot'),
    ('ROV', 'Rover'),
    ('TATA', 'Tata'),
    ('ZOO', 'Zotye'),
    ('DAI', 'Daihatsu'),
    ('ISU', 'Isuzu'),
    ('SEAT', 'SEAT'),
    ('SKO', 'Skoda'),
    ('OPL', 'Opel'),
    ('FISK', 'Fisker'),
    ('LEGO', 'Lego'),
    ('RUF', 'Ruf'),
]

MODEL_YEARS = [
    ('1980', '1980'),
    ('1981', '1981'),
    ('1982', '1982'),
    ('1983', '1983'),
    ('1984', '1984'),
    ('1985', '1985'),
    ('1986', '1986'),
    ('1987', '1987'),
    ('1988', '1988'),
    ('1989', '1989'),
    ('1990', '1990'),
    ('1991', '1991'),
    ('1992', '1992'),
    ('1993', '1993'),
    ('1994', '1994'),
    ('1995', '1995'),
    ('1996', '1996'),
    ('1997', '1997'),
    ('1998', '1998'),
    ('1999', '1999'),
    ('2000', '2000'),
    ('2001', '2001'),
    ('2002', '2002'),
    ('2003', '2003'),
    ('2004', '2004'),
    ('2005', '2005'),
    ('2006', '2006'),
    ('2007', '2007'),
    ('2008', '2008'),
    ('2009', '2009'),
    ('2010', '2010'),
    ('2011', '2011'),
    ('2012', '2012'),
    ('2013', '2013'),
    ('2014', '2014'),
    ('2015', '2015'),
    ('2016', '2016'),
    ('2017', '2017'),
    ('2018', '2018'),
    ('2019', '2019'),
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),
    ('2024', '2024'),
]

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




