# Generated by Django 4.2.11 on 2024-08-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakwheel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Car',
        ),
    ]
