# Generated by Django 4.2.11 on 2024-08-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakwheel', '0002_rename_team_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='User',
        ),
    ]
