# Generated by Django 4.2.11 on 2024-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carlisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=255)),
                ('make', models.CharField(choices=[('TOY', 'Toyota'), ('BMW', 'BMW'), ('MER', 'Mercedes-Benz'), ('HON', 'Honda'), ('AUD', 'Audi'), ('LEX', 'Lexus'), ('FORD', 'Ford'), ('CHE', 'Chevrolet'), ('VOL', 'Volvo'), ('MAZ', 'Mazda'), ('NIS', 'Nissan'), ('SUB', 'Subaru'), ('VW', 'Volkswagen'), ('JAG', 'Jaguar'), ('PORS', 'Porsche'), ('LAND', 'Land Rover'), ('RAN', 'Ram'), ('KIA', 'Kia'), ('HYU', 'Hyundai'), ('ACU', 'Acura'), ('LIN', 'Lincoln'), ('INFI', 'Infiniti'), ('MIN', 'MINI'), ('BU', 'Buick'), ('CAD', 'Cadillac'), ('MITS', 'Mitsubishi'), ('CHRY', 'Chrysler'), ('FIAT', 'Fiat'), ('ALP', 'Alfa Romeo'), ('MAS', 'Maserati'), ('AST', 'Aston Martin'), ('FERR', 'Ferrari'), ('TES', 'Tesla'), ('RAM', 'Ram'), ('SAAB', 'Saab'), ('GMC', 'GMC'), ('JEEP', 'Jeep'), ('PEU', 'Peugeot'), ('ROV', 'Rover'), ('TATA', 'Tata'), ('ZOO', 'Zotye'), ('DAI', 'Daihatsu'), ('ISU', 'Isuzu'), ('SEAT', 'SEAT'), ('SKO', 'Skoda'), ('OPL', 'Opel'), ('FISK', 'Fisker'), ('LEGO', 'Lego'), ('RUF', 'Ruf')], max_length=9)),
                ('modelyear', models.PositiveIntegerField(choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')])),
                ('image', models.ImageField(upload_to='home/hash/Desktop/Projects/DJango/pakwheelproject/pakwheelproject/static')),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('SOLD', 'Sold'), ('PEND', 'Pending')], default='AVL', max_length=4)),
            ],
        ),
    ]
