# Generated by Django 4.2.11 on 2024-08-31 09:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_carlisting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter a valid phone number.', max_length=128, region=None, verbose_name='Phone Number')),
            ],
        ),
    ]
