# Generated by Django 4.2.11 on 2024-08-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fname',
        ),
    ]
