# Generated by Django 4.2.11 on 2024-08-31 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0005_remove_contact_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='listing_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
